/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.wuhailong.imagecrawer.ui;

import cn.wuhailong.imagecrawer.main.ImageCrawler;
import cn.wuhailong.imagecrawer.QueueAndSet.LinkQueue;
import cn.wuhailong.imagecrawer.domain.LinkEntry;
import cn.wuhailong.imagecrawer.settings.Settings;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 程序入口，主界面
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seedField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seedField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        seedField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        seedField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        seedField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seedField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        urlStartField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        imgUrlStartField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        imgUrlStartField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        imgUrlStartField3 = new javax.swing.JTextField();
        urlStartField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        urlStartField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        downImageFileDirectoryField = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        imgMinSizeField = new javax.swing.JTextField();
        imgMaxSizeField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        speedCom = new javax.swing.JComboBox<>();
        endBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        urlKeyField1 = new javax.swing.JTextField();
        urlKeyField3 = new javax.swing.JTextField();
        urlKeyField2 = new javax.swing.JTextField();
        imgUrlKeyField1 = new javax.swing.JTextField();
        imgUrlKeyField2 = new javax.swing.JTextField();
        imgUrlKeyField3 = new javax.swing.JTextField();
        urlKeyCB1 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        downNum = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        visitedImgNum = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        unVisitedImgNum = new javax.swing.JLabel();
        visitedUrlNum = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        unVisitedUrlNum = new javax.swing.JLabel();
        urlKeyCB2 = new javax.swing.JCheckBox();
        urlKeyCB3 = new javax.swing.JCheckBox();
        imgUrlKeyCB1 = new javax.swing.JCheckBox();
        imgUrlKeyCB2 = new javax.swing.JCheckBox();
        imgUrlKeyCB3 = new javax.swing.JCheckBox();
        urlKeyOutField1 = new javax.swing.JTextField();
        urlKeyOutField2 = new javax.swing.JTextField();
        urlKeyOutField3 = new javax.swing.JTextField();
        imgUrlKeyOutField1 = new javax.swing.JTextField();
        imgUrlKeyOutField2 = new javax.swing.JTextField();
        imgUrlKeyOutField3 = new javax.swing.JTextField();
        urlKeyOutCB1 = new javax.swing.JCheckBox();
        urlKeyOutCB2 = new javax.swing.JCheckBox();
        urlKeyOutCB3 = new javax.swing.JCheckBox();
        imgUrlKeyOutCB1 = new javax.swing.JCheckBox();
        imgUrlKeyOutCB2 = new javax.swing.JCheckBox();
        imgUrlKeyOutCB3 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("图片蚂蚁");
        setName(""); // NOI18N
        setResizable(false);

        seedField1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("起始网页：");

        jLabel2.setText("1");

        jLabel3.setText("2");

        seedField2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("3");

        seedField3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("4");

        seedField4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("5");

        seedField5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setText("6");

        seedField6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setText("3");

        urlStartField3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("1");

        imgUrlStartField1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setText("2");

        imgUrlStartField2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setText("3");

        imgUrlStartField3.setBackground(new java.awt.Color(204, 204, 255));

        urlStartField1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setText("连接地址过滤：");

        jLabel13.setText("1");

        jLabel14.setText("2");

        urlStartField2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel15.setText("图片地址过滤：");

        jLabel16.setText("图片存放目录：");

        downImageFileDirectoryField.setBackground(new java.awt.Color(255, 153, 255));
        downImageFileDirectoryField.setText("F:\\temp");

        startBtn.setBackground(new java.awt.Color(0, 204, 0));
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("开始运行");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        stopBtn.setBackground(new java.awt.Color(51, 51, 255));
        stopBtn.setForeground(new java.awt.Color(255, 255, 255));
        stopBtn.setText("暂停运行");
        stopBtn.setEnabled(false);
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("图片大小过滤：");

        imgMinSizeField.setBackground(new java.awt.Color(204, 255, 255));
        imgMinSizeField.setText("30");

        imgMaxSizeField.setBackground(new java.awt.Color(204, 255, 255));
        imgMaxSizeField.setText("10240");

        jLabel19.setText("K    -    ");

        jLabel20.setText("K");

        jLabel21.setText("爬取速度控制：");

        speedCom.setBackground(new java.awt.Color(204, 204, 204));
        speedCom.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        speedCom.setForeground(new java.awt.Color(51, 51, 255));
        speedCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "5", "8", "10", "20", "50", "100", "200", "500", "1000", "最大速度" }));
        speedCom.setSelectedIndex(9);

        endBtn.setBackground(new java.awt.Color(255, 153, 0));
        endBtn.setForeground(new java.awt.Color(255, 255, 255));
        endBtn.setText("终止");
        endBtn.setEnabled(false);
        endBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBtnActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("微软雅黑", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 255));
        jLabel26.setText("图片爬虫");

        jLabel27.setForeground(new java.awt.Color(153, 51, 255));
        jLabel27.setText("version 0.1");

        urlKeyField1.setBackground(new java.awt.Color(255, 255, 204));

        urlKeyField3.setBackground(new java.awt.Color(255, 255, 204));

        urlKeyField2.setBackground(new java.awt.Color(255, 255, 204));

        imgUrlKeyField1.setBackground(new java.awt.Color(204, 204, 255));

        imgUrlKeyField2.setBackground(new java.awt.Color(204, 204, 255));

        imgUrlKeyField3.setBackground(new java.awt.Color(204, 204, 255));

        urlKeyCB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setForeground(new java.awt.Color(0, 204, 255));
        jLabel28.setText("关键字过滤：");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setText("下载图片数：");

        downNum.setFont(new java.awt.Font("楷体", 1, 36)); // NOI18N
        downNum.setForeground(new java.awt.Color(204, 51, 255));
        downNum.setText("0");

        jLabel22.setText("已爬取图片数：");

        visitedImgNum.setText("0");

        jLabel23.setText("待爬取图片数：");

        unVisitedImgNum.setText("0");

        visitedUrlNum.setText("0");

        jLabel24.setText("已爬取网页数：");

        jLabel25.setText("待爬取网页数：");

        unVisitedUrlNum.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visitedImgNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unVisitedImgNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitedUrlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unVisitedUrlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downNum)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(visitedImgNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(unVisitedImgNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitedUrlNum)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(unVisitedUrlNum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        urlKeyCB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        urlKeyCB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyCB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyCB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyCB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        urlKeyOutField1.setBackground(new java.awt.Color(255, 255, 204));

        urlKeyOutField2.setBackground(new java.awt.Color(255, 255, 204));

        urlKeyOutField3.setBackground(new java.awt.Color(255, 255, 204));

        imgUrlKeyOutField1.setBackground(new java.awt.Color(204, 204, 255));

        imgUrlKeyOutField2.setBackground(new java.awt.Color(204, 204, 255));

        imgUrlKeyOutField3.setBackground(new java.awt.Color(204, 204, 255));

        urlKeyOutCB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        urlKeyOutCB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        urlKeyOutCB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyOutCB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyOutCB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgUrlKeyOutCB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setForeground(new java.awt.Color(0, 204, 255));
        jLabel29.setText("包含(空格分隔）：");

        jLabel30.setForeground(new java.awt.Color(0, 204, 255));
        jLabel30.setText("不包含(空格分隔）：");

        jLabel31.setForeground(new java.awt.Color(0, 204, 255));
        jLabel31.setText("链接头部限制：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(65, 65, 65)
                                        .addComponent(imgMinSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imgMaxSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(speedCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(downImageFileDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(imgUrlStartField3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(imgUrlKeyField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seedField1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(seedField6, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seedField5))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seedField4))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seedField3))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(seedField2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(imgUrlStartField2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(imgUrlStartField1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(urlStartField3))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(urlStartField2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(urlStartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imgUrlKeyField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imgUrlKeyField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(urlKeyField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(urlKeyField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(urlKeyField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(urlKeyCB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlKeyOutField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urlKeyOutCB3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(urlKeyCB2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(urlKeyOutField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(urlKeyOutCB2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imgUrlKeyCB1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgUrlKeyOutField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgUrlKeyOutCB1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imgUrlKeyCB2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgUrlKeyOutField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgUrlKeyOutCB2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imgUrlKeyCB3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgUrlKeyOutField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imgUrlKeyOutCB3)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(urlKeyCB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(urlKeyOutField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(urlKeyOutCB1)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seedField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlStartField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(urlKeyField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(urlKeyCB1)
                    .addComponent(urlKeyOutField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlKeyOutCB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlStartField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(urlKeyField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(urlKeyCB2)
                    .addComponent(urlKeyOutField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlKeyOutCB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlStartField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(urlKeyField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(urlKeyCB3)
                    .addComponent(urlKeyOutField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlKeyOutCB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(imgUrlStartField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel15)
                                .addComponent(imgUrlKeyField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imgUrlKeyCB1)
                            .addComponent(imgUrlKeyOutField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(imgUrlStartField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(imgUrlKeyField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(imgUrlKeyCB2)
                                    .addComponent(imgUrlKeyOutCB2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(imgUrlStartField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(imgUrlKeyField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(imgMinSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18)
                                            .addComponent(imgMaxSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(downImageFileDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(speedCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imgUrlKeyCB3)
                                            .addComponent(imgUrlKeyOutField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imgUrlKeyOutCB3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(endBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(imgUrlKeyOutField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgUrlKeyOutCB1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * “开始运行”按钮点击执行
    */
    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        
        //开始运行设置
        startSet();
        
        //启动
        crawlerStart();
        
        //修改按钮状态
        startBtn.setEnabled(false);
        stopBtn.setEnabled(true);
        endBtn.setEnabled(true);
    }//GEN-LAST:event_startBtnActionPerformed

    /*
    * 获取起始网页并保存设置
    */
    private void setFirstUrl(Settings settings){
        String seed1 = seedField1.getText();
        String seed2 = seedField2.getText();
        String seed3 = seedField3.getText();
        String seed4 = seedField4.getText();
        String seed5 = seedField5.getText();
        String seed6 = seedField6.getText();
        String[] seeds = {seed1, seed2, seed3, seed4, seed5, seed6};
        settings.setSeeds(seeds);
    }
    
    /*
    * 获取网页地址过滤信息并保存设置
    */
    private void setUrlStart(Settings settings){
        LinkEntry entry1 = new LinkEntry();
        entry1.setLink(urlStartField1.getText().trim());
        if(urlKeyCB1.isSelected()){
            String key = urlKeyField1.getText();
            
            //根据空格拆分字符串
            String[] keys = key.split("\\s+");
            
            entry1.setKeys(keys);
        }else{
            entry1.setKeys(null);
        }
        if(urlKeyOutCB1.isSelected()){
            String key = urlKeyOutField1.getText();
            String[] keys = key.split("\\s+");
            entry1.setKeyOuts(keys);
        }else{
            entry1.setKeyOuts(null);
        }
        LinkEntry entry2 = new LinkEntry();
        entry2.setLink(urlStartField2.getText().trim());
        if(urlKeyCB2.isSelected()){
            String key = urlKeyField2.getText();
            String[] keys = key.split("\\s+");
            entry2.setKeys(keys);
        }else{
            entry2.setKeys(null);
        }
        if(urlKeyOutCB2.isSelected()){
            String key = urlKeyOutField2.getText();
            String[] keys = key.split("\\s+");
            entry2.setKeyOuts(keys);
        }else{
            entry2.setKeyOuts(null);
        }
        LinkEntry entry3 = new LinkEntry();
        entry3.setLink(urlStartField3.getText().trim());
        if(urlKeyCB3.isSelected()){
            String key = urlKeyField3.getText();
            String[] keys = key.split("\\s+");
            entry3.setKeys(keys);
        }else{
            entry3.setKeys(null);
        }
        if(urlKeyOutCB3.isSelected()){
            String key = urlKeyOutField3.getText();
            String[] keys = key.split("\\s+");
            entry3.setKeyOuts(keys);
        }else{
            entry3.setKeyOuts(null);
        }
        List<LinkEntry> entrys = new ArrayList<LinkEntry>();
        entrys.add(entry1);
        entrys.add(entry2);
        entrys.add(entry3);
        settings.setUrlStarts(entrys);
    }
    
    /*
    * 获取图片地址过滤信息并保存设置
    */
    private void setImgUrlStart(Settings settings){
        LinkEntry imgEntry1 = new LinkEntry();
        imgEntry1.setLink(imgUrlStartField1.getText().trim());
        if(imgUrlKeyCB1.isSelected()){
            String key = imgUrlKeyField1.getText();
            String[] keys = key.split("\\s+");
            imgEntry1.setKeys(keys);
        }else{
            imgEntry1.setKeys(null);
        }
        if(imgUrlKeyOutCB1.isSelected()){
            String key = imgUrlKeyOutField1.getText();
            String[] keys = key.split("\\s+");
            imgEntry1.setKeyOuts(keys);
        }else{
            imgEntry1.setKeyOuts(null);
        }
        LinkEntry imgEntry2 = new LinkEntry();
        imgEntry2.setLink(imgUrlStartField2.getText().trim());
        if(imgUrlKeyCB2.isSelected()){
            String key = imgUrlKeyField2.getText();
            String[] keys = key.split("\\s+");
            imgEntry2.setKeys(keys);
        }else{
            imgEntry2.setKeys(null);
        }
        if(imgUrlKeyOutCB2.isSelected()){
            String key = imgUrlKeyOutField2.getText();
            String[] keys = key.split("\\s+");
            imgEntry2.setKeyOuts(keys);
        }else{
            imgEntry2.setKeyOuts(null);
        }
        LinkEntry imgEntry3 = new LinkEntry();
        imgEntry3.setLink(imgUrlStartField3.getText().trim());
        if(imgUrlKeyCB3.isSelected()){
            String key = imgUrlKeyField3.getText();
            String[] keys = key.split("\\s+");
            imgEntry3.setKeys(keys);
        }else{
            imgEntry3.setKeys(null);
        }
        if(imgUrlKeyOutCB3.isSelected()){
            String key = imgUrlKeyOutField3.getText();
            String[] keys = key.split("\\s+");
            imgEntry3.setKeyOuts(keys);
        }else{
            imgEntry3.setKeyOuts(null);
        }
        List<LinkEntry> imgEntrys = new ArrayList<LinkEntry>();
        imgEntrys.add(imgEntry1);
        imgEntrys.add(imgEntry2);
        imgEntrys.add(imgEntry3);
        settings.setImgUrlStarts(imgEntrys);
    }
    
    /*
    * 获取图片大小限制并保存设置
    */
    private void setImgSize(Settings settings){
        int imgMinSize = 2*1024;
        try{
            imgMinSize = Integer.valueOf(imgMinSizeField.getText()) * 1024;
        }catch(NumberFormatException ex){}
        int imgMaxSize = 20*1024*1024;
        try{
            imgMaxSize = Integer.valueOf(imgMaxSizeField.getText()) * 1024;
        }catch(NumberFormatException ex){}
        settings.setImgMinSize(imgMinSize);
        settings.setImgMaxSize(imgMaxSize);
    }
    
    /*
    * 开始运行设置
    */
    private void startSet(){
        //获取配置类
        Settings settings = Settings.getInstance();
        
        //设置起始网页
        setFirstUrl(settings);
        
        //获取网页地址过滤信息并保存设置
        setUrlStart(settings);
        
        //获取图片地址过滤信息并保存设置
        setImgUrlStart(settings);
        
        
        //获取图片大小限制并保存设置
        setImgSize(settings);
        
        //获取图片存放目录并保存设置
        String filePath = downImageFileDirectoryField.getText();
        filePath = filePath.replace("\\", "\\\\");
        settings.setFilePath(filePath);
        
        //获取速度并保存设置
        int speed = 10;
        String speedText = (String) speedCom.getSelectedItem();
        if("最大速度".equals(speedText)){
            speed =10000;
        }else{
            try{
                speed = Integer.valueOf(speedText);
            }catch(NumberFormatException ex){}
        }
        settings.setSpeed(speed);        
        
        //设置运行信号
        settings.setStart(true);
    }
    
    /*
    * 启动
    */
    private void crawlerStart(){
        //新建爬取线程，并运行
        Thread crawThread = new Thread(new Runnable() {
            @Override
            public void run() {
                crawler.startCrawler();
            }
        });
        crawThread.start();
        
        //新建界面刷新线程，并运行
        Thread showThread = new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    int down_num = LinkQueue.getDownImgNum();
                    downNum.setText( down_num+"");
                    visitedImgNum.setText(LinkQueue.getVisitedImgUrlNum()+"");
                    unVisitedImgNum.setText(LinkQueue.getUnVisitedImgUrlNum()+"");
                    visitedUrlNum.setText(LinkQueue.getVisitedUrlNum()+"");
                    unVisitedUrlNum.setText(LinkQueue.getUnVisitedUrlNum() +"");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {}
                }
            }
        });
        showThread.start();
    }
    
    /*
    * "暂停运行/恢复运行"按钮操作
    */
    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        //获取配置类
        Settings settings = Settings.getInstance();
        //如果正在运行，设置运行信号为false,修改按钮显示信息为“恢复运行”，否则（未运行），设置运行信号为true,修改按钮显示信息为“暂停运行”
        if(settings.isStart()){
            //在“暂停运行”时，因为后续无需清空队列和其他操作，所以无需主动关闭线程池，直接等待其线程全部执行完毕。
            settings.setStart(false);
            stopBtn.setText("恢复运行");
        }else{
            settings.setStart(true);
            crawlerStart();
            stopBtn.setText("暂停运行");
        }
    }//GEN-LAST:event_stopBtnActionPerformed

    /*
    * “终止/复位”按钮操作
    */
    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBtnActionPerformed
        /*
        * 如果按钮为“复位”
        */
        if("复位".equals(endBtn.getText())){
            //下载图片数归零
            LinkQueue.resetDownImgNum();
            
            //再次刷新队列
            //注：因为终止时已经等待所有下载线程同步，所以其实不必须，此处仅是一重保护
            LinkQueue.reset();
            
            //修改按钮状态和显示
            startBtn.setEnabled(true);
            endBtn.setText("终止");
            endBtn.setEnabled(false);
        }else{
        /*
        * 如果按钮为“终止”
        */
            //获取配置类，这是运行信号为false
            Settings settings = Settings.getInstance();
            settings.setStart(false);
            
            /*
            * 此处休息500ms，等待爬虫核心类的主线程和以下两个线程结束
            * 一：读取网页队列的线程
            * 二：读物图片队列的线程
            */
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            /*
            * 读取网页队列和图片队列的线程已结束，此处关闭两个线程池
            * 等待分析网页的线程全部结束，等待下载图片的线程全部结束
            * 在结束前将不会执行队列重置方法
            */
            crawler.stopCrawler();
            
            //队列重置，清空所有已下载和待下载的网页和图片队列
            LinkQueue.reset();
            
            //修改按钮状态
            stopBtn.setEnabled(false);
            endBtn.setText("复位");
        }
        
    }//GEN-LAST:event_endBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    //图片爬虫核心程序类初始化
    private ImageCrawler crawler = new ImageCrawler();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField downImageFileDirectoryField;
    private javax.swing.JLabel downNum;
    private javax.swing.JButton endBtn;
    private javax.swing.JTextField imgMaxSizeField;
    private javax.swing.JTextField imgMinSizeField;
    private javax.swing.JCheckBox imgUrlKeyCB1;
    private javax.swing.JCheckBox imgUrlKeyCB2;
    private javax.swing.JCheckBox imgUrlKeyCB3;
    private javax.swing.JTextField imgUrlKeyField1;
    private javax.swing.JTextField imgUrlKeyField2;
    private javax.swing.JTextField imgUrlKeyField3;
    private javax.swing.JCheckBox imgUrlKeyOutCB1;
    private javax.swing.JCheckBox imgUrlKeyOutCB2;
    private javax.swing.JCheckBox imgUrlKeyOutCB3;
    private javax.swing.JTextField imgUrlKeyOutField1;
    private javax.swing.JTextField imgUrlKeyOutField2;
    private javax.swing.JTextField imgUrlKeyOutField3;
    private javax.swing.JTextField imgUrlStartField1;
    private javax.swing.JTextField imgUrlStartField2;
    private javax.swing.JTextField imgUrlStartField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField seedField1;
    private javax.swing.JTextField seedField2;
    private javax.swing.JTextField seedField3;
    private javax.swing.JTextField seedField4;
    private javax.swing.JTextField seedField5;
    private javax.swing.JTextField seedField6;
    private javax.swing.JComboBox<String> speedCom;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel unVisitedImgNum;
    private javax.swing.JLabel unVisitedUrlNum;
    private javax.swing.JCheckBox urlKeyCB1;
    private javax.swing.JCheckBox urlKeyCB2;
    private javax.swing.JCheckBox urlKeyCB3;
    private javax.swing.JTextField urlKeyField1;
    private javax.swing.JTextField urlKeyField2;
    private javax.swing.JTextField urlKeyField3;
    private javax.swing.JCheckBox urlKeyOutCB1;
    private javax.swing.JCheckBox urlKeyOutCB2;
    private javax.swing.JCheckBox urlKeyOutCB3;
    private javax.swing.JTextField urlKeyOutField1;
    private javax.swing.JTextField urlKeyOutField2;
    private javax.swing.JTextField urlKeyOutField3;
    private javax.swing.JTextField urlStartField1;
    private javax.swing.JTextField urlStartField2;
    private javax.swing.JTextField urlStartField3;
    private javax.swing.JLabel visitedImgNum;
    private javax.swing.JLabel visitedUrlNum;
    // End of variables declaration//GEN-END:variables
}
